package logic.util.enumeration;

/* Enumerazione delle varie scene utile in caso di switch*/

public enum Views {
	HOME,LOGIN,MYACCOUNT,MYGROUPS,MYRESERVATIONS,MYREVIEWS,MYROOMS,ROOMSEARCH,
	OTHERACCOUNT,POSTROOM,REVIEWFORM,GROUPBOOKING,GROUPCREATION,NAVBAR,REGISTRATION,ADDGROUPMEMBER
}
